[build]
#target = "xtensa-esp32-espidf"
target = "riscv32imc-esp-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
rustflags = [ "--cfg",  "espidf_time64" ]

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
rustflags = [ "--cfg",  "espidf_time64" ]

[unstable]
build-std = ["std", "panic_abort"]

[env]
#__CARGO_TEST_CHANNEL_OVERRIDE_DO_NOT_USE_THIS="nightly"
RUSTC_BOOTSTRAP="1"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.1.1"
